# Generated by Django 4.2 on 2023-12-09 11:45

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonato',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('campeonato', smart_selects.db_fields.ChainedForeignKey(chained_field='liga_id', chained_model_field='liga_id', on_delete=django.db.models.deletion.CASCADE, related_name='campeonato_id', to='core.campeonato')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=200)),
                ('campeonato', smart_selects.db_fields.ChainedForeignKey(chained_field='liga_id', chained_model_field='liga_id', on_delete=django.db.models.deletion.CASCADE, related_name='campeon_id', to='core.campeonato')),
                ('categoria', smart_selects.db_fields.ChainedForeignKey(chained_field='campeonato', chained_model_field='campeonato', on_delete=django.db.models.deletion.CASCADE, related_name='categor_id', to='core.categoria')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('campeonato', smart_selects.db_fields.ChainedForeignKey(chained_field='liga_id', chained_model_field='liga_id', on_delete=django.db.models.deletion.CASCADE, related_name='campeonat_id', to='core.campeonato')),
                ('categoria', smart_selects.db_fields.ChainedForeignKey(chained_field='campeonato', chained_model_field='campeonato', on_delete=django.db.models.deletion.CASCADE, related_name='categoria_id', to='core.categoria')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('carrera_uno', models.IntegerField(default=0, verbose_name='Carreras Equipo A')),
                ('carrera_dos', models.IntegerField(default=0, verbose_name='Carreras Equipo B')),
                ('error_uno', models.IntegerField(default=0, verbose_name='Errores Equipo A')),
                ('error_dos', models.IntegerField(default=0, verbose_name='Errores Equipo B')),
                ('hits_uno', models.IntegerField(default=0, verbose_name='Hits Equipo A')),
                ('hits_dos', models.IntegerField(default=0, verbose_name='Hits Equipo B')),
                ('campeonato', smart_selects.db_fields.ChainedForeignKey(chained_field='liga_id', chained_model_field='liga_id', on_delete=django.db.models.deletion.CASCADE, related_name='cam_id', to='core.campeonato')),
                ('categoria', smart_selects.db_fields.ChainedForeignKey(chained_field='campeonato', chained_model_field='campeonato', on_delete=django.db.models.deletion.CASCADE, related_name='cat_id', to='core.categoria')),
                ('equipo_dos', smart_selects.db_fields.ChainedForeignKey(chained_field='grupob', chained_model_field='grupo', on_delete=django.db.models.deletion.CASCADE, related_name='equipo_dos_id', to='core.equipo', verbose_name='Equipo B')),
                ('equipo_uno', smart_selects.db_fields.ChainedForeignKey(chained_field='grupo', chained_model_field='grupo', on_delete=django.db.models.deletion.CASCADE, related_name='equipo_uno_id', to='core.equipo', verbose_name='Equipo A')),
                ('grupo', smart_selects.db_fields.ChainedForeignKey(chained_field='categoria', chained_model_field='categoria', on_delete=django.db.models.deletion.CASCADE, related_name='gp_id', to='core.grupo', verbose_name='Grupo Equipo A')),
                ('grupob', smart_selects.db_fields.ChainedForeignKey(chained_field='categoria', chained_model_field='categoria', on_delete=django.db.models.deletion.CASCADE, related_name='gpb_id', to='core.grupo', verbose_name='Grupo Equipo B')),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Pitcher', 'Pitcher'), ('Bateador', 'Bateador')], max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('campeonato', smart_selects.db_fields.ChainedForeignKey(chained_field='liga_id', chained_model_field='liga_id', on_delete=django.db.models.deletion.CASCADE, related_name='camp_id', to='core.campeonato')),
                ('categoria', smart_selects.db_fields.ChainedForeignKey(chained_field='campeonato', chained_model_field='campeonato', on_delete=django.db.models.deletion.CASCADE, related_name='categ_id', to='core.categoria')),
                ('equipo', smart_selects.db_fields.ChainedForeignKey(chained_field='grupo', chained_model_field='grupo', on_delete=django.db.models.deletion.CASCADE, related_name='equipo_id', to='core.equipo')),
                ('grupo', smart_selects.db_fields.ChainedForeignKey(chained_field='categoria', chained_model_field='categoria', on_delete=django.db.models.deletion.CASCADE, related_name='grup_id', to='core.grupo')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('titulo_uno', models.CharField(max_length=200)),
                ('titulo_dos', models.CharField(max_length=200)),
                ('periodo', models.CharField(max_length=200, verbose_name='Período')),
                ('logo', models.ImageField(upload_to='')),
                ('anno', models.IntegerField(verbose_name='Año')),
                ('responsable', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResumenEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugados', models.IntegerField(default=0, verbose_name='Juegos Jugados')),
                ('ganados', models.IntegerField(default=0, verbose_name='Juegos Ganados')),
                ('perdidos', models.IntegerField(default=0, verbose_name='Juegos Perdidos')),
                ('empatados', models.IntegerField(default=0, verbose_name='Juegos Empatados')),
                ('pct', models.IntegerField(default=0, verbose_name='PCT')),
                ('campeonato', smart_selects.db_fields.ChainedForeignKey(chained_field='liga_id', chained_model_field='liga_id', on_delete=django.db.models.deletion.CASCADE, related_name='campc_id', to='core.campeonato')),
                ('categoria', smart_selects.db_fields.ChainedForeignKey(chained_field='campeonato', chained_model_field='campeonato', on_delete=django.db.models.deletion.CASCADE, related_name='categc_id', to='core.categoria')),
                ('equipo', smart_selects.db_fields.ChainedForeignKey(chained_field='grupo', chained_model_field='grupo', on_delete=django.db.models.deletion.CASCADE, related_name='equipoc_id', to='core.equipo')),
                ('grupo', smart_selects.db_fields.ChainedForeignKey(chained_field='categoria', chained_model_field='categoria', on_delete=django.db.models.deletion.CASCADE, related_name='grupc_id', to='core.grupo')),
                ('liga_id', models.ForeignKey(db_column='liga_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.liga', verbose_name='Liga')),
            ],
            options={
                'verbose_name': 'Resumen Equipo',
                'verbose_name_plural': 'Resumen Equipos',
                'db_table': '',
                'ordering': ['-ganados'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pitcheo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganado', models.BooleanField(verbose_name='Juego Ganado')),
                ('perdido', models.BooleanField(verbose_name='Juego Perdido')),
                ('sin_decision', models.BooleanField(verbose_name='Juego Sin Decisión')),
                ('hits', models.IntegerField(default=0, verbose_name='Hits Permitidos')),
                ('ip', models.IntegerField(default=0, verbose_name='IP')),
                ('carreras', models.IntegerField(default=0, verbose_name='Carreras permitidas')),
                ('carr_limpias', models.IntegerField(default=0, verbose_name='Carreras limpias')),
                ('ponche', models.IntegerField(default=0, verbose_name='Ponches')),
                ('bb', models.IntegerField(default=0, verbose_name='Base por bolas')),
                ('pcl', models.FloatField(blank=True, default=0, editable=False, null=True)),
                ('pcte', models.FloatField(blank=True, default=0, editable=False, null=True)),
                ('campeonato', smart_selects.db_fields.ChainedForeignKey(chained_field='liga_id', chained_model_field='liga_id', on_delete=django.db.models.deletion.CASCADE, related_name='cambp_id', to='core.campeonato')),
                ('categoria', smart_selects.db_fields.ChainedForeignKey(chained_field='campeonato', chained_model_field='campeonato', on_delete=django.db.models.deletion.CASCADE, related_name='catbp_id', to='core.categoria')),
                ('equipo', smart_selects.db_fields.ChainedForeignKey(chained_field='categoria', chained_model_field='categoria', on_delete=django.db.models.deletion.CASCADE, related_name='equipp_id', to='core.equipo', verbose_name='Equipo')),
                ('grupo', smart_selects.db_fields.ChainedForeignKey(chained_field='categoria', chained_model_field='categoria', on_delete=django.db.models.deletion.CASCADE, related_name='gpbatp_id', to='core.grupo', verbose_name='Grupo')),
                ('juego', smart_selects.db_fields.ChainedForeignKey(chained_field='grupo', chained_model_field='grupo', on_delete=django.db.models.deletion.CASCADE, related_name='juep_id', to='core.juego', verbose_name='Juego')),
                ('jugador_id', smart_selects.db_fields.ChainedForeignKey(chained_field='equipo', chained_model_field='equipo', on_delete=django.db.models.deletion.CASCADE, related_name='jugadorp_id', to='core.jugador', verbose_name='Jugador')),
                ('liga_id', models.ForeignKey(db_column='liga_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.liga', verbose_name='Liga')),
            ],
            options={
                'verbose_name': 'Pitcheo',
                'verbose_name_plural': 'Pitcheos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='jugador',
            name='liga_id',
            field=models.ForeignKey(db_column='liga_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.liga', verbose_name='Liga'),
        ),
        migrations.AddField(
            model_name='juego',
            name='liga_id',
            field=models.ForeignKey(db_column='liga_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.liga', verbose_name='Liga'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='liga_id',
            field=models.ForeignKey(db_column='liga_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.liga', verbose_name='Liga'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='grupo',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='categoria', chained_model_field='categoria', on_delete=django.db.models.deletion.CASCADE, related_name='grupo_id', to='core.grupo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='liga_id',
            field=models.ForeignKey(db_column='liga_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.liga', verbose_name='Liga'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='liga_id',
            field=models.ForeignKey(db_column='liga_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.liga', verbose_name='Liga'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='liga_id',
            field=models.ForeignKey(db_column='liga_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.liga', verbose_name='Liga'),
        ),
        migrations.CreateModel(
            name='Bateo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veces_bate', models.IntegerField(default=0, verbose_name='Veces al Bate')),
                ('hits', models.IntegerField(default=0, verbose_name='Hits')),
                ('doble', models.IntegerField(default=0, verbose_name='Dobles')),
                ('triple', models.IntegerField(default=0, verbose_name='Triples')),
                ('home_run', models.IntegerField(default=0, verbose_name='Home Run')),
                ('carrera', models.IntegerField(default=0, verbose_name='Carreras')),
                ('base_robada', models.IntegerField(default=0, verbose_name='Bases robadas')),
                ('base_bola', models.IntegerField(default=0, verbose_name='Bases por bolas')),
                ('ponche', models.IntegerField(default=0, verbose_name='Ponches')),
                ('campeonato', smart_selects.db_fields.ChainedForeignKey(chained_field='liga_id', chained_model_field='liga_id', on_delete=django.db.models.deletion.CASCADE, related_name='camb_id', to='core.campeonato')),
                ('categoria', smart_selects.db_fields.ChainedForeignKey(chained_field='campeonato', chained_model_field='campeonato', on_delete=django.db.models.deletion.CASCADE, related_name='catb_id', to='core.categoria')),
                ('equipo', smart_selects.db_fields.ChainedForeignKey(chained_field='categoria', chained_model_field='categoria', on_delete=django.db.models.deletion.CASCADE, related_name='equip_id', to='core.equipo', verbose_name='Equipo')),
                ('grupo', smart_selects.db_fields.ChainedForeignKey(chained_field='categoria', chained_model_field='categoria', on_delete=django.db.models.deletion.CASCADE, related_name='gpbat_id', to='core.grupo', verbose_name='Grupo')),
                ('juego', smart_selects.db_fields.ChainedForeignKey(chained_field='grupo', chained_model_field='grupo', on_delete=django.db.models.deletion.CASCADE, related_name='jue_id', to='core.juego', verbose_name='Juego')),
                ('jugador_id', smart_selects.db_fields.ChainedForeignKey(chained_field='equipo', chained_model_field='equipo', on_delete=django.db.models.deletion.CASCADE, related_name='jugador_id', to='core.jugador', verbose_name='Jugador')),
                ('liga_id', models.ForeignKey(db_column='liga_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.liga', verbose_name='Liga')),
            ],
            options={
                'verbose_name': 'Bateo',
                'verbose_name_plural': 'Bateos',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
