# Generated by Django 4.2 on 2023-12-06 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('carrera_uno', models.IntegerField(verbose_name='Carreras Equipo A')),
                ('carrera_dos', models.IntegerField(verbose_name='Carreras Equipo B')),
                ('error_uno', models.IntegerField(verbose_name='Errores Equipo A')),
                ('error_dos', models.IntegerField(verbose_name='Errores Equipo B')),
                ('hits_uno', models.IntegerField(verbose_name='Hits Equipo A')),
                ('hits_dos', models.IntegerField(verbose_name='Hits Equipo B')),
                ('campo_id', models.ForeignKey(db_column='campo_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.campo', verbose_name='Lugar')),
                ('equipo_dos', models.ForeignKey(db_column='equipo_dos', on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipo_perdedor', to='core.equipo', verbose_name='Equipo B')),
                ('equipo_uno', models.ForeignKey(db_column='equipo_uno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.equipo', verbose_name='Equipo A')),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Pitcher', 'Pitcher'), ('Bateador', 'Bateador')], max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('equipo_id', models.ForeignKey(db_column='equipo_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResumenEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugados', models.IntegerField(verbose_name='Juegos Jugados')),
                ('ganados', models.IntegerField(verbose_name='Juegos Ganados')),
                ('perdidos', models.IntegerField(verbose_name='Juegos Perdidos')),
                ('empatados', models.IntegerField(verbose_name='Juegos Empatados')),
                ('pct', models.IntegerField(verbose_name='PCT')),
                ('equipo', models.ForeignKey(db_column='equipo_uno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Resumen Equipo',
                'verbose_name_plural': 'Resumen Equipos',
                'db_table': '',
                'ordering': ['-ganados'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pitcheo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganado', models.BooleanField(verbose_name='Juego Ganado')),
                ('perdido', models.BooleanField(verbose_name='Juego Perdido')),
                ('sin_decision', models.BooleanField(verbose_name='Juego Sin Decisión')),
                ('hits', models.IntegerField(verbose_name='Hits Permitidos')),
                ('ip', models.IntegerField(verbose_name='IP')),
                ('carreras', models.IntegerField(verbose_name='Carreras permitidas')),
                ('carr_limpias', models.IntegerField(verbose_name='Carreras limpias')),
                ('ponche', models.IntegerField(verbose_name='Ponches')),
                ('bb', models.IntegerField(verbose_name='Base por bolas')),
                ('pcl', models.FloatField(blank=True, editable=False, null=True)),
                ('pcte', models.FloatField(blank=True, editable=False, null=True)),
                ('juego_id', models.ForeignKey(db_column='juego_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.juego', verbose_name='Juego')),
                ('jugador_id', models.ForeignKey(db_column='jugador_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.jugador', verbose_name='Pitcher')),
            ],
            options={
                'verbose_name': 'Pitcheo',
                'verbose_name_plural': 'Pitcheos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('titulo_uno', models.CharField(max_length=200)),
                ('titulo_dos', models.CharField(max_length=200)),
                ('periodo', models.CharField(max_length=200, verbose_name='Período')),
                ('logo', models.ImageField(upload_to='')),
                ('anno', models.IntegerField(verbose_name='Año')),
                ('responsable', models.CharField(max_length=100)),
                ('categoria_id', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria', verbose_name='Categoría')),
                ('temporada_id', models.ForeignKey(db_column='temporada_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.temporada', verbose_name='Temporada')),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('liga_id', models.ForeignKey(db_column='liga_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.liga', verbose_name='Liga')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='grupo_id',
            field=models.ForeignKey(db_column='grupo_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.grupo', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='liga_id',
            field=models.ForeignKey(db_column='liga_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.liga', verbose_name='Liga'),
        ),
        migrations.CreateModel(
            name='Bateo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veces_bate', models.IntegerField(verbose_name='Veces al Bate')),
                ('hits', models.IntegerField(verbose_name='Hits')),
                ('doble', models.IntegerField(verbose_name='Dobles')),
                ('triple', models.IntegerField(verbose_name='Triples')),
                ('home_run', models.IntegerField(verbose_name='Home Run')),
                ('carrera', models.IntegerField(verbose_name='Carreras')),
                ('base_robada', models.IntegerField(verbose_name='Bases robadas')),
                ('base_bola', models.IntegerField(verbose_name='Bases por bolas')),
                ('ponche', models.IntegerField(verbose_name='Ponches')),
                ('juego_id', models.ForeignKey(db_column='juego_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.juego', verbose_name='Juego')),
                ('jugador_id', models.ForeignKey(db_column='jugador_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.jugador', verbose_name='Bateador')),
            ],
            options={
                'verbose_name': 'Bateo',
                'verbose_name_plural': 'Bateos',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
