# Generated by Django 4.2 on 2023-12-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_campo_categoria_equipo_juego_jugador_pitcheo_liga_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jugador',
            options={'managed': True, 'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.RemoveField(
            model_name='pitcheo',
            name='jugado',
        ),
        migrations.RemoveField(
            model_name='pitcheo',
            name='veces',
        ),
        migrations.AlterField(
            model_name='pitcheo',
            name='pcl',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='pitcheo',
            name='pcte',
            field=models.FloatField(editable=False),
        ),
    ]
