# Generated by Django 4.2 on 2023-12-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_equipo_grupo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='grupo_id',
            new_name='grupo',
        ),
    ]
