# Generated by Django 4.2 on 2023-12-06 22:18

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_grupo_id_equipo_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='liga_id',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='liga_id',
        ),
        migrations.AddField(
            model_name='equipo',
            name='liga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.liga'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='liga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.liga'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipo',
            name='grupo',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='liga', chained_model_field='liga', on_delete=django.db.models.deletion.CASCADE, to='core.grupo'),
        ),
    ]
