# Generated by Django 4.2 on 2023-12-05 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_jugador_options_remove_pitcheo_jugado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitcheo',
            name='bb',
            field=models.IntegerField(verbose_name='Base por bolas'),
        ),
        migrations.AlterField(
            model_name='pitcheo',
            name='carr_limpias',
            field=models.IntegerField(verbose_name='Carreras limpias'),
        ),
        migrations.AlterField(
            model_name='pitcheo',
            name='carreras',
            field=models.IntegerField(verbose_name='Carreras permitidas'),
        ),
        migrations.AlterField(
            model_name='pitcheo',
            name='ganado',
            field=models.BooleanField(verbose_name='Juego Ganado'),
        ),
        migrations.AlterField(
            model_name='pitcheo',
            name='hits',
            field=models.IntegerField(verbose_name='Hits Permitidos'),
        ),
        migrations.AlterField(
            model_name='pitcheo',
            name='ip',
            field=models.IntegerField(verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='pitcheo',
            name='juego_id',
            field=models.ForeignKey(db_column='juego_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.juego', verbose_name='Juego'),
        ),
        migrations.AlterField(
            model_name='pitcheo',
            name='jugador_id',
            field=models.ForeignKey(db_column='jugador_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.jugador', verbose_name='Jugador'),
        ),
        migrations.AlterField(
            model_name='pitcheo',
            name='perdido',
            field=models.BooleanField(verbose_name='Juego Perdido'),
        ),
        migrations.AlterField(
            model_name='pitcheo',
            name='ponche',
            field=models.IntegerField(verbose_name='Ponches'),
        ),
        migrations.AlterField(
            model_name='pitcheo',
            name='sin_decision',
            field=models.BooleanField(verbose_name='Juego Sin Decisión'),
        ),
    ]
