# Generated by Django 4.2 on 2023-12-05 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pitcheo_bb_alter_pitcheo_carr_limpias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='tipo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bateo',
            name='base_bola',
            field=models.IntegerField(verbose_name='Bases por bolas'),
        ),
        migrations.AlterField(
            model_name='bateo',
            name='base_robada',
            field=models.IntegerField(verbose_name='Bases robadas'),
        ),
        migrations.AlterField(
            model_name='bateo',
            name='carrera',
            field=models.IntegerField(verbose_name='Carreras'),
        ),
        migrations.AlterField(
            model_name='bateo',
            name='doble',
            field=models.IntegerField(verbose_name='Dobles'),
        ),
        migrations.AlterField(
            model_name='bateo',
            name='hits',
            field=models.IntegerField(verbose_name='Hits'),
        ),
        migrations.AlterField(
            model_name='bateo',
            name='home_run',
            field=models.IntegerField(verbose_name='Home Run'),
        ),
        migrations.AlterField(
            model_name='bateo',
            name='juego_id',
            field=models.ForeignKey(db_column='juego_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.juego', verbose_name='Juego'),
        ),
        migrations.AlterField(
            model_name='bateo',
            name='jugador_id',
            field=models.ForeignKey(db_column='jugador_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.jugador', verbose_name='Jugador'),
        ),
        migrations.AlterField(
            model_name='bateo',
            name='ponche',
            field=models.IntegerField(verbose_name='Ponches'),
        ),
        migrations.AlterField(
            model_name='bateo',
            name='triple',
            field=models.IntegerField(verbose_name='Triples'),
        ),
        migrations.AlterField(
            model_name='bateo',
            name='veces_bate',
            field=models.IntegerField(verbose_name='Veces al Bate'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='grupo_id',
            field=models.ForeignKey(db_column='grupo_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.grupo', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='campo_id',
            field=models.ForeignKey(db_column='campo_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.campo', verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='liga',
            name='anno',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='liga',
            name='categoria_id',
            field=models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='liga',
            name='periodo',
            field=models.CharField(max_length=200, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='liga',
            name='temporada_id',
            field=models.ForeignKey(db_column='temporada_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.temporada', verbose_name='Temporada'),
        ),
    ]
